version: '3.9'

services:
  pop-node:
    environment:
     - POP_CONFIG_PATH=/root/pipe/config.json
     - POP_INVITE_CODE=YTOUR_CODE
    build: .
    container_name: pop-node
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /root/pop-data:/root/pipe
      - ./start.sh:/start.sh
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5
